version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    # environment:
    #   - FLASK_ENV=development
    # command: python app.py




